# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fkrieger/Documents/Projects/openNTT/OpenNTT_Github/vivado/vivado.srcs/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_xbar_0/OpenNTT_BD_xbar_0.xci
# IP: The module: 'OpenNTT_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Documents/Projects/openNTT/OpenNTT_Github/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_xbar_0/OpenNTT_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fkrieger/Documents/Projects/openNTT/OpenNTT_Github/vivado/vivado.srcs/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_xbar_0/OpenNTT_BD_xbar_0.xci
# IP: The module: 'OpenNTT_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Documents/Projects/openNTT/OpenNTT_Github/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_xbar_0/OpenNTT_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
