# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/OpenNTT_BD/OpenNTT_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD || ORIG_REF_NAME==OpenNTT_BD} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_axi_bram_ctrl_0_0/OpenNTT_BD_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_axi_bram_ctrl_0_0 || ORIG_REF_NAME==OpenNTT_BD_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_axi_cdma_0_0 || ORIG_REF_NAME==OpenNTT_BD_axi_cdma_0_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_xbar_0/OpenNTT_BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_xbar_0 || ORIG_REF_NAME==OpenNTT_BD_xbar_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_axi_interconnect_0_0/OpenNTT_BD_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_axi_interconnect_0_0 || ORIG_REF_NAME==OpenNTT_BD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_processing_system7_0_0/OpenNTT_BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_processing_system7_0_0 || ORIG_REF_NAME==OpenNTT_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_ps7_0_axi_periph_0/OpenNTT_BD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==OpenNTT_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_ps7_0_axi_periph_1_0/OpenNTT_BD_ps7_0_axi_periph_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==OpenNTT_BD_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_rst_ps7_0_100M_0/OpenNTT_BD_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==OpenNTT_BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_AXISlave8Ports_1_0/OpenNTT_BD_AXISlave8Ports_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_AXISlave8Ports_1_0 || ORIG_REF_NAME==OpenNTT_BD_AXISlave8Ports_1_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_ComputeCoreWrapper_0_0/OpenNTT_BD_ComputeCoreWrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_ComputeCoreWrapper_0_0 || ORIG_REF_NAME==OpenNTT_BD_ComputeCoreWrapper_0_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_auto_pc_0/OpenNTT_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_auto_pc_0 || ORIG_REF_NAME==OpenNTT_BD_auto_pc_0} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_auto_pc_1/OpenNTT_BD_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_auto_pc_1 || ORIG_REF_NAME==OpenNTT_BD_auto_pc_1} -quiet] -quiet

# IP: bd/OpenNTT_BD/ip/OpenNTT_BD_auto_pc_2/OpenNTT_BD_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OpenNTT_BD_auto_pc_2 || ORIG_REF_NAME==OpenNTT_BD_auto_pc_2} -quiet] -quiet

# XDC: /home/fkrieger/Documents/openNTT/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/OpenNTT_BD_ooc.xdc
