# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fkrieger/Desktop/openNTT/vivado/vivado.srcs/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0.xci
# IP: The module: 'OpenNTT_BD_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Desktop/openNTT/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fkrieger/Desktop/openNTT/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fkrieger/Desktop/openNTT/vivado/vivado.srcs/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0.xci
# IP: The module: 'OpenNTT_BD_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Desktop/openNTT/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fkrieger/Desktop/openNTT/vivado/vivado.gen/sources_1/bd/OpenNTT_BD/ip/OpenNTT_BD_axi_cdma_0_0/OpenNTT_BD_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OpenNTT_BD_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
